name: zeppelin
summary: Zeppelin, a web-based notebook that enables interactive data analytics
description: |
 You can make beautiful data-driven, interactive and collaborative documents
 with SQL, Scala and more.

 Core feature:
  * Web based notebook style editor.
  * Built-in Apache Spark support
version: "0.6.2"
confinement: devmode
grade: devel
apps:
    zeppelin:
        command: snap.sh
        plugs: [network-bind, process-control]
        daemon: forking
parts:
  zeppelin:
    plugin: dump
    source: http://mirror.cc.columbia.edu/pub/software/apache/zeppelin/zeppelin-0.6.2/zeppelin-0.6.2-bin-all.tgz
  jdk:
    plugin: nil
    stage-packages:
      - default-jdk
  glue:
    plugin: dump
    source: .
    snap:
      - snap.sh
